### ISSUE TITLE
CRC-32 checksum is not correct

### ISSUE THREAD

**Issue by Somebodyisnobody** [westberliner/checksum#32]
The CRC-32 algorithm is not equal if i check the same file with https://emn178.github.io/online-tools/crc32_checksum.html and 7-Zip. I tested that with 2 files.

The other algorithms are correct

**Comment by Manorhos** [comment]
PHP provides two different CRC32 algorithms and the `crc32b` variant appears to be more widely used as a file checksum.
So either we need to add CRC32b as an additional checksum choice or we could just switch over to `crc32b` altogether.
Personally, I'd prefer the latter.

**Comment by Somebodyisnobody** [comment]
Oh I didn't now that, thought CRC32 = CRC32 😃

**Comment by westberliner** [comment]
I added crc32b as well.
