### ISSUE TITLE
Does not work in app groups folders

### ISSUE THREAD

**Issue by layz89** [westberliner/checksum#38]
Checksum does not work in the App Groups folder:
https://apps.nextcloud.com/apps/groupfolders

**Comment by Ajilis** [comment]
does its works for a simple folder ?

**Comment by st3iny** [comment]
I just tested creating a checksum of a file within a group folder and it worked just fine. This issue was most likely fixed by https://github.com/westberliner/checksum/pull/47.

@westberliner You can close this issue.

**Comment by Ajilis** [comment]
Do you think we can create checksum for folders ?

**Comment by st3iny** [comment]
@Ajilis Currently, creating checksums for entire folders is not implemented. There are open issues related to that feature: #23, #51
