### ISSUE TITLE
NC19 compatibility

### ISSUE THREAD

**Issue by tflidd** [westberliner/checksum#42]
I just activated the app on a NC 19RC2 setup on a FreeBSD/nginx/php7.3 environment. Didn't see any errors so far.
Would be good if someone with knowledge to the code could take a look before pushing the number of supported version.

**Comment by SeekDaSky** [comment]
I activated the extension on NC19, hosted on Arch linux with PHP 7.4.5, no issues so far.

**Comment by westberliner** [comment]
Will deploy an update today.

**Comment by reiner-text** [comment]
> Will deploy an update today.

Please push the update to the [AppStore](https://apps.nextcloud.com/apps/checksum), too. Thanks!

**Comment by westberliner** [comment]
I wanted to see #44. I tried for several days. Now it worked. Is released.

**Comment by reiner-text** [comment]
Sorry, I missed #44.

**Comment by westberliner** [comment]
Nevermind :) This notification reminded me to check it again.
