### ISSUE TITLE
Will not work in future Nextcloud versions

### ISSUE THREAD

**Issue by JonathanTreffler** [westberliner/checksum#45]
To create a Tab in the File Sidebar this App uses [fileList.registerTabView()](https://github.com/westberliner/checksum/blob/9f073f18b63821d29d623bb010b8ff67c297e995/js/checksum.plugin.js#L21) and that function [will be removed in Nextcloud 20](
).

It might me a good idea to migrate to the [new API](https://github.com/nextcloud/server/blob/master/apps/files/src/sidebar.js) before Nextcloud 20 gets released.

**Comment by e-alfred** [comment]
Same problem for the Printer app: https://github.com/e-alfred/nextcloud-printer

**Comment by KG3RK3N** [comment]
I have checked the current version with nextcloud 20 and it works. But you're right that a migration needed for future versions of nextcloud.

@st3iny 
I have see your fork and it seems that you are already work on a version that use the new API, right?

**Comment by st3iny** [comment]
Yes, my fork is updated and refactored. This repository uses deprecated parts of the nextcloud api and does not work reliably on newer nextcloud versions (e.g. it breaks when using object storage as primary storage).

Ref #46

**Comment by westberliner** [comment]
Further discussions in #46.
