### ISSUE TITLE
Update to recent Nextcloud versions

### ISSUE THREAD

**Issue by st3iny** [westberliner/checksum#46]
I forked and updated this app to work with nextcloud v20 and v21. I refactored the usage of the deprecated nextcloud api and leveraged the new server container interface and the abstract storage backend. This means that my fork is now independent of the used storage backend. However, those changes are not compatible with owncloud.

I would be happy to send a PR if you are willing to drop support for owncloud.
Feel free to close this issue if not.

**Comment by slawa-dev** [comment]
Nice work. I hope maintainer can act on it as the NC v20 is being rolled out to everyone.

```
Compatibility
    It should be safe for future versions.
```
😅

**Comment by Zocker1999NET** [comment]
@st3iny Could you please, if @westberliner does decide in favor of owncloud, upload your version of the app to the store, so users/admins can easier "migrate" to your fixed version?

**Comment by westberliner** [comment]
Hi, sry. Somehow I get only notifications if someone mentions me. I guess dropping support for OC is fine. The community of NC is by far more active. If you have a PR just let me know. If not I will look into the API changes as well.

**Comment by st3iny** [comment]
@westberliner Awesome! I will prepare a PR and mention you when it's ready. Thank you for maintaining this app :)

**Comment by westberliner** [comment]
Nvm, thank you for the PR :) And sorry that you had to wait for so long.
