### ISSUE TITLE
Is this app also supported on PHP 7.3/7.2?

### ISSUE THREAD

**Issue by Zocker1999NET** [westberliner/checksum#49]
The `app.xml` states, that a PHP version of 7.4 is required to run the app while `README.md` states, that the app was only tested on PHP 7.4. As Nextcloud states in the [official manual for version 20](https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html), it recommends PHP 7.3/7.4, but also supports 7.2.

So, my question is, is this app known to not work on versions below 7.4 or could a static code analysis / real tests show, that the app also works on 7.2/7.3 and so the minimum version of PHP required could set to an older version? I would help testing if it is not hopeless from the beginning.

I ask because I use Debian Stable which will hold on to [PHP 7.3](https://packages.debian.org/buster/php) until the next release of Bullseye in hopefully summer 2021, I do not want to use another package source than the official Debian repository and also because of Nextcloud still recommending 7.3 beside supporting 7.2, I think I'm not the only person with this problem.

**Comment by tavinus** [comment]
+1  
Before updating to NC20 I had no problems with this.  
Now it is blacklisted for that PHP7.4 requirement.  
Can we please have this cleared for php 7.3?

**Comment by jolang** [comment]
@westberliner is there a technical reason you set the required PHP version to 7.4 with the last release?

**Comment by westberliner** [comment]
I will check it. Should be possible to allow PHP7.2 - as NC 20 recommends as well. Was an overside of mine. Sry for that. I'll keep you posted.

**Comment by westberliner** [comment]
The latest updated typed class properties. That is why. I removed them for now and released an update on [apps.nextcloud.com](https://apps.nextcloud.com/apps/checksum).

**Comment by st3iny** [comment]
Oops, I forgot to check the PHP version compatibility when sending the PR. Thanks for fixing @westberliner.
