### ISSUE TITLE
Transifex project URL?

### ISSUE THREAD

**Issue by p-bo** [westberliner/checksum#57]
Hi,

noticed config for Transifex there, but cannot find on list in Nextcloud project on Transifex. May I ask you for help where to translate please?

Thanks :-)

**Comment by westberliner** [comment]
Hi, I issued a PR to start translating via transifex. If the PR is accepted by nextcloud I will update the readme for an howto. 

Thx for contributing and sorry for the late response.

**Comment by westberliner** [comment]
In progress: https://github.com/nextcloud/docker-ci/issues/333

**Comment by p-bo** [comment]
Great, will translate into Czech immediately :-)

**Comment by p-bo** [comment]
Done, closing - thanks for fixing this!
