### ISSUE TITLE
CRC32 show wrong result

### ISSUE THREAD

**Issue by aldevan** [westberliner/checksum#60]
hi, in same file MD5, SHA1 and others ok, but in CRC32 show wrong result as can you can see in print https://i.ibb.co/8P9hJm8/crc32-wrong.png

**Comment by westberliner** [comment]
This issue was discussed here: https://github.com/westberliner/checksum/issues/32.
But you mention it as well. I will check if I find a way to avoid this confusion.

Thx for mentioning it.

**Comment by westberliner** [comment]
Forgot to close this issue. Already an option. You may choose between crc32 and crc32b.
