### ISSUE TITLE
Add Nextcloud 24 compatibility

### ISSUE THREAD

**Issue by ximex** [westberliner/checksum#64]
Pls make it compatible with Nextcloud 24

**Comment by westberliner** [comment]
Hi, will do.

**Comment by westberliner** [comment]
I released an update for NC24. Feel free to download it [directly](https://github.com/westberliner/checksum/releases/tag/v1.1.4) or via [app store](https://apps.nextcloud.com/apps/checksum).

**Comment by westberliner** [comment]
I tested it with NC24. Worked for me. If still an issue occurs I would be nice to get a new Issue here. 

Kind Regards
Patrick
