### ISSUE TITLE
"Choose algorithm" drop-down is unusable in NextCloud 23

### ISSUE THREAD

**Issue by GuyPaddock** [westberliner/checksum#68]
On Nextcloud 23.0.10, the drop-down for selecting an algorithm doesn't render correctly in either Chrome/Edge or Firefox:
![image](https://user-images.githubusercontent.com/2631799/195254955-cc494abf-90b0-43b0-82d2-3980ab4f2e11.png)

**Comment by westberliner** [comment]
Hm, I'll try to reproduce the issue.

**Comment by westberliner** [comment]
Hi, 

I tested it with OC 23.0.10 with the current releases of the checksum app (1.1.4), Firefox (106.0.1), and Chrome (106.0.x). I cannot reproduce your issue. I'll close it for now. Feel free to open this anytime if you have an idea to reproduce this issue.
