### ISSUE TITLE
Clarify process to join Transifex via URL in docs

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [westberliner/checksum#70]
Thanks for the great work here!

I noticed you added the project to transifex and everything seemes to have worked on nextcloud side as well as of [5 Jan 2021](aaca878c314e592cb886c89893d7d56ed17dacc6850ea08db6f47425b5942a494a9e51ffb33b3e2539e3b5a78a2cd00847910a9ea11ba5a06792722fddc409185023c74d12ba9d434dbfb49213
). Anyway now the [transifex project URL you share in the README](https://www.transifex.com/nextcloud/search/?q=resource%3Achecksum) does not work anymore and I was not able to find your project there: https://explore.transifex.com/search/?q=checksum.

**Comment by p-bo** [comment]
@BjoernLudwigPTB resource for this app is normally there
![obrazek](https://user-images.githubusercontent.com/12208593/200287021-e1065921-9808-4f06-9cf3-34f63d72e33c.png)
and URL you mentioned is functional.

**Comment by BjoernLudwigPTB** [comment]
Ah okay, that just works after visiting https://explore.transifex.com/nextcloud/nextcloud/ and there clicking "Join this project". Otherwise you get as only answer:

```
{"message": "Forbidden"}
```
when visiting https://www.transifex.com/nextcloud/search/?q=resource%3Achecksum and searching for checksum anywhere on _transifex.com_ be it in- or outside of the nextcloud organisation yields no results.

Thanks for just confirming that everything should work. I would recommend to mention the necessity to join the nextcloud organization before being able to visit your link and will provide a short PR, if you like.

**Comment by p-bo** [comment]
I see, so correct URL, where to translate is https://www.transifex.com/nextcloud/nextcloud/checksum/ then one will get either Transifex login page, or Join Nextcloud project (cannot walk trough, because I`m already joined by my account). In both cases when one is joined into Nextcloud project on Transifex, there is then Translate button and one can start translating/improving. So I you want, please do PR with this URL (perhaps that it is needed to join project there on Transifex - but it is standard on this platform).

**Comment by BjoernLudwigPTB** [comment]
I changed the title. Could you please assign me?

**Comment by p-bo** [comment]
@BjoernLudwigPTB only maintainers of this repository can do this (not my case - mere translator). But you can do PR with fix of readme regardless of assignment of this issue report. Maintainers then will review and (if it fits) merge it.

**Comment by BjoernLudwigPTB** [comment]
> @BjoernLudwigPTB only maintainers of this repository can do this (not my case - mere translator). But you can do PR with fix of readme regardless of assignment of this issue report. Maintainers then will review and (if it fits) merge it.

Ah yes, sure… I did not pay any attention with whom I am communicating here. Sorry, to bother you. Of course this is not a blocker for contributing, just would help me to organise things.

@westberliner Could you assign me?

**Comment by BjoernLudwigPTB** [comment]
@westberliner Your suggestion sounds good to me. At least it is the until now missing hint, that there is a preceeding step, to being able to collaborate.

**Comment by westberliner** [comment]
Readme updated. Thx for mentioning this.
