### ISSUE TITLE
Remove old algorithms and add SHA3

### ISSUE THREAD

**Issue by tuxmaster5000** [westberliner/checksum#74]
The new  and less cpu intensive SHA3 algorithms is missing.
And the old algorithms shout be removed or add the option to disable it by the admin.

**Comment by westberliner** [comment]
Hi, extend the list with sha3 is easy. Will do.
Settings menu is on my todo: https://github.com/westberliner/checksum/issues/17
I was to lazy so far to implement. ;)

**Comment by westberliner** [comment]
Added in v1.2.0. The settings part is in #17.
