### ISSUE TITLE
[1.1.5] Strange settings area

### ISSUE THREAD

**Issue by tuxmaster5000** [westberliner/checksum#75]
The admin settings are very strange. An button and an check box without any real description.
![Screenshot 2022-11-19 at 19-10-13](https://user-images.githubusercontent.com/837503/202865520-f983446d-dffa-4b82-82e8-5b0749536b7d.png)

**Comment by datenzar** [comment]
@westberliner My guess: the app needs to adjust for a NC25 breaking change 
"If your app is made with vue, migrate away from icon-class to vue material design icons" (https://github.com/nextcloud/server/issues/32060)

**Comment by tuxmaster5000** [comment]
It will happens on NC24. I don't use NC25 until now.

**Comment by westberliner** [comment]
I screwed this one up. Still in development but got into production. Will release an update and remove it.

**Comment by westberliner** [comment]
Released v1.2.0. Thx for mentioning.
