### ISSUE TITLE
0.3.6 version not available on owncloud marketplace?

### ISSUE THREAD

**Issue by nodens** [westberliner/checksum#77]
Hi,

According to #67 3.6 has been pushed to owncloud's marketplace, but when I check https://marketplace.owncloud.com/apps/checksum it seems to still be 3.5.

Am I looking in the wrong place?

Thanks!

**Comment by nodens** [comment]
Side but related question: have you given up completely on OwnCloud to support NextCloud only?

Thanks!

**Comment by nodens** [comment]
FYI, In order to bring back the app to our users after our 10.11 owncloud upgrade, I installed manually from a `git checkout v0.3.6.1", and I noticed the version in `appinfo/info.xml` is still 0.3.5. Maybe that's the reason why it doesn't appear in owncloud market? BTW, just replacing the version string  to 0.3.6.1 worked fine for me.

Could you please upload again in owncloud market?

Thanks!

**Comment by westberliner** [comment]
I rechecked. Somehow it needed to be published. I can see now the version 0.3.6. I hope you too.
