### ISSUE TITLE
Version for NC28

### ISSUE THREAD

**Issue by tflidd** [westberliner/checksum#86]
A new Nextcloud version is out. It would be great to see this app in NC28 ;-)

**Comment by Albirew** [comment]
well... it seems it's working on my NxC 28.0.1 tho...

**Comment by aol-nnov** [comment]
> it seems it's working on my NxC 28.0.1 tho...

Well, actually, it is, but I had to click "enable untested app" as it was automatically disabled during update.

Either way, it'd be good if author/maintainers would bump compatibility metadata at least..
